### ISSUE TITLE
no such target @local_config_nccl//:nccl_headers

### ISSUE THREAD

**Issue by apivovarov** [openxla/xla#17326]
Error:
```bash
bazel build //xla/tsl/cuda:nccl

ERROR: /home/ubuntu/workspace/xla/xla/tsl/cuda/BUILD.bazel:336:11: no such target '@local_config_nccl//:nccl_headers': target 'nccl_headers' not declared in package '' defined by /home/ubuntu/.cache/bazel/_bazel_ubuntu/0176aac02e77df836cc7203737c26784/external/local_config_nccl/BUILD (Tip: use `query "@local_config_nccl//:*"` to see all the targets in that package) and referenced by '//xla/tsl/cuda:nccl'
ERROR: Analysis of target '//xla/tsl/cuda:nccl' failed; build aborted: Analysis failed

bazel build //xla/...

ERROR: /home/ubuntu/workspace/xla/xla/tsl/cuda/BUILD.bazel:336:11: no such target '@local_config_nccl//:nccl_headers': target 'nccl_headers' not declared in package '' defined by /home/ubuntu/.cache/bazel/_bazel_ubuntu/0176aac02e77df836cc7203737c26784/external/local_config_nccl/BUILD (Tip: use `query "@local_config_nccl//:*"` to see all the targets in that package) and referenced by '//xla/tsl/cuda:nccl'
ERROR: Analysis of target '//xla/tsl/cuda:nccl' failed; build aborted: Analysis failed
```

Bazel Query:
```bash
bazel query @local_config_nccl//:*

@local_config_nccl//:BUILD
@local_config_nccl//:LICENSE
@local_config_nccl//:nccl
@local_config_nccl//:nccl_config
@local_config_nccl//:nccl_config.h
```

**Comment by apivovarov** [comment]
Hi David, could you help with triaging and assigning this issue? It blocks `//xla/tsl/..` testing on GPU.

@ddunl

**Comment by ddunl** [comment]
Ah I see - I'm wondering if there's some interaction here with hermetic cuda.

**Comment by sergachev** [comment]
Related (following https://openxla.org/xla/lsp):

```
bazel aquery "mnemonic(CppCompile, //xla/...)" --output=jsonproto
...
xla/xla/tsl/cuda/BUILD.bazel:336:11: no such target '@local_config_nccl//:nccl_headers': target 'nccl_headers' not declared in package '' defined by ...
```

**Comment by sergachev** [comment]
And for me this fixes the problem, at least in a setup not using NCCL: https://github.com/openxla/xla/pull/17369

**Comment by ybaturina** [comment]
I've submitted the fix in https://github.com/openxla/xla/pull/17377. Please let me know if it works for you.

**Comment by sergachev** [comment]
> I've submitted the fix in https://github.com/openxla/xla/pull/17377. Please let me know if it works for you.

Works for me.

**Comment by apivovarov** [comment]
`bazel build //xla/tsl/cuda:nccl` - works fine now. Thank you!
